# tell travis to run tests on a macintosh CI
language: objective-c

install:

  # sync rubymotion version to CI
- sudo chown -R travis ~/Library/RubyMotion
- mkdir -p ~/Library/RubyMotion/build

  # the following version number is duplicated in README.md and Rakefile
- sudo motion update --cache-version=3.10

- bundle install

script:
- bundle exec rake spec
